INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (1, N'Điện thoại/Laptop/Tablet', N'Điện thoại/Laptop/Tablet', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (2, N'Điện thoại', N'Điện thoại', NULL, 1);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (3, N'Laptop', N'Laptop', NULL, 1);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (4, N'Tablet', N'Tablet', NULL, 1);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (5, N'Điện máy - Điện lạnh', N'Điện máy - Điện lạnh', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (6, N'Tivi', N'Tivi', NULL, 5);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (7, N'Tủ lạnh', N'Tủ lạnh', NULL, 5);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (8, N'Điều hòa', N'Điều hòa', NULL, 5);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (9, N'Phụ kiện', N'Phụ kiện', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (10, N'USB', N'USB', NULL, 9);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (11, N'Sạc dự phòng', N'Sạc dự phòng', NULL, 9);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (12, N'Tai nghe bluetooth', N'Tai nghe bluetooth', NULL, 9);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (13, N'Chuột', N'Chuột', NULL, 9);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (14, N'Cáp', N'Cáp', NULL, 9);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (15, N'Đồng hồ', N'Đồng hồ', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (16, N'Đồng hồ Thông minh', N'Đồng hồ Thông minh', NULL, 15);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (17, N'Đồng hồ Thời trang', N'Đồng hồ Thời trang', NULL, 15);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (18, N'Vali/Ba lô/Túi xách', N'Vali/Ba lô/Túi xách', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (19, N'Vali', N'Vali', NULL, 18);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (20, N'Ba lô', N'Ba lô', NULL, 18);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (21, N'Túi xách', N'Túi xách', NULL, 18);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (22, N'Trang sức', N'Trang sức', NULL, NULL);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (23, N'Nhẫn', N'Nhẫn', NULL, 22);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (24, N'Dây chuyền', N'Dây chuyền', NULL, 22);
INSERT INTO "Loai" ("MaLoai", "TenLoai", "MoTa", "Hinh", "MaLoaiCha") VALUES (25, N'Kim cương', N'Kim cương', NULL, 22);
